
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE1_SOC(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// HPS //////////
	inout 		          		HPS_CONV_USB_N,
	output		    [14:0]		HPS_DDR3_ADDR,
	output		     [2:0]		HPS_DDR3_BA,
	output		          		HPS_DDR3_CAS_N,
	output		          		HPS_DDR3_CKE,
	output		          		HPS_DDR3_CK_N,
	output		          		HPS_DDR3_CK_P,
	output		          		HPS_DDR3_CS_N,
	output		     [3:0]		HPS_DDR3_DM,
	inout 		    [31:0]		HPS_DDR3_DQ,
	inout 		     [3:0]		HPS_DDR3_DQS_N,
	inout 		     [3:0]		HPS_DDR3_DQS_P,
	output		          		HPS_DDR3_ODT,
	output		          		HPS_DDR3_RAS_N,
	output		          		HPS_DDR3_RESET_N,
	input 		          		HPS_DDR3_RZQ,
	output		          		HPS_DDR3_WE_N,
	output		          		HPS_ENET_GTX_CLK,
	inout 		          		HPS_ENET_INT_N,
	output		          		HPS_ENET_MDC,
	inout 		          		HPS_ENET_MDIO,
	input 		          		HPS_ENET_RX_CLK,
	input 		     [3:0]		HPS_ENET_RX_DATA,
	input 		          		HPS_ENET_RX_DV,
	output		     [3:0]		HPS_ENET_TX_DATA,
	output		          		HPS_ENET_TX_EN,
	inout 		     [3:0]		HPS_FLASH_DATA,
	output		          		HPS_FLASH_DCLK,
	output		          		HPS_FLASH_NCSO,
	inout 		     [1:0]		HPS_GPIO,
	inout 		          		HPS_GSENSOR_INT,
	inout 		          		HPS_I2C1_SCLK,
	inout 		          		HPS_I2C1_SDAT,
	inout 		          		HPS_I2C2_SCLK,
	inout 		          		HPS_I2C2_SDAT,
	inout 		          		HPS_I2C_CONTROL,
	inout 		          		HPS_KEY,
	inout 		          		HPS_LED,
	output		          		HPS_SD_CLK,
	inout 		          		HPS_SD_CMD,
	inout 		     [3:0]		HPS_SD_DATA,
	output		          		HPS_SPIM_CLK,
	input 		          		HPS_SPIM_MISO,
	output		          		HPS_SPIM_MOSI,
	inout 		          		HPS_SPIM_SS,
	input 		          		HPS_UART_RX,
	output		          		HPS_UART_TX,
	input 		          		HPS_USB_CLKOUT,
	inout 		     [7:0]		HPS_USB_DATA,
	input 		          		HPS_USB_DIR,
	input 		          		HPS_USB_NXT,
	output		          		HPS_USB_STP,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO0GPIO,

	//////////// GPIO_1, GPIO_1 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO1GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================
design u0 (
         .system_pll_ref_clk_clk              (CLOCK_50),             //   pll_ref_clk.clk
         .system_pll_ref_reset_reset          (!KEY[0]),						// pll_ref_reset.reset
			.sdram_clk_clk							 (),
		  
			  //Mem            
				.memory_mem_a			(HPS_DDR3_ADDR),
				.memory_mem_ba			(HPS_DDR3_BA),
				.memory_mem_ck			(HPS_DDR3_CK_P),
				.memory_mem_ck_n		(HPS_DDR3_CK_N),
				.memory_mem_cke		(HPS_DDR3_CKE),
				.memory_mem_cs_n		(HPS_DDR3_CS_N),
				.memory_mem_ras_n		(HPS_DDR3_RAS_N),
				.memory_mem_cas_n		(HPS_DDR3_CAS_N),
				.memory_mem_we_n		(HPS_DDR3_WE_N),
				.memory_mem_reset_n	(HPS_DDR3_RESET_N),
				.memory_mem_dq			(HPS_DDR3_DQ),
				.memory_mem_dqs		(HPS_DDR3_DQS_P),
				.memory_mem_dqs_n		(HPS_DDR3_DQS_N),
				.memory_mem_odt		(HPS_DDR3_ODT),
				.memory_mem_dm			(HPS_DDR3_DM),
				.memory_oct_rzqin		(HPS_DDR3_RZQ),
		
			 // Ethernet
				.hps_io_hps_io_gpio_inst_GPIO35	(HPS_ENET_INT_N),
				.hps_io_hps_io_emac1_inst_TX_CLK	(HPS_ENET_GTX_CLK),
				.hps_io_hps_io_emac1_inst_TXD0	(HPS_ENET_TX_DATA[0]),
				.hps_io_hps_io_emac1_inst_TXD1	(HPS_ENET_TX_DATA[1]),
				.hps_io_hps_io_emac1_inst_TXD2	(HPS_ENET_TX_DATA[2]),
				.hps_io_hps_io_emac1_inst_TXD3	(HPS_ENET_TX_DATA[3]),
				.hps_io_hps_io_emac1_inst_RXD0	(HPS_ENET_RX_DATA[0]),
				.hps_io_hps_io_emac1_inst_MDIO	(HPS_ENET_MDIO),
				.hps_io_hps_io_emac1_inst_MDC		(HPS_ENET_MDC),
				.hps_io_hps_io_emac1_inst_RX_CTL	(HPS_ENET_RX_DV),
				.hps_io_hps_io_emac1_inst_TX_CTL	(HPS_ENET_TX_EN),
				.hps_io_hps_io_emac1_inst_RX_CLK	(HPS_ENET_RX_CLK),
				.hps_io_hps_io_emac1_inst_RXD1	(HPS_ENET_RX_DATA[1]),
				.hps_io_hps_io_emac1_inst_RXD2	(HPS_ENET_RX_DATA[2]),
				.hps_io_hps_io_emac1_inst_RXD3	(HPS_ENET_RX_DATA[3]),

				// Flash
				.hps_io_hps_io_qspi_inst_IO0	(HPS_FLASH_DATA[0]),
				.hps_io_hps_io_qspi_inst_IO1	(HPS_FLASH_DATA[1]),
				.hps_io_hps_io_qspi_inst_IO2	(HPS_FLASH_DATA[2]),
				.hps_io_hps_io_qspi_inst_IO3	(HPS_FLASH_DATA[3]),
				.hps_io_hps_io_qspi_inst_SS0	(HPS_FLASH_NCSO),
				.hps_io_hps_io_qspi_inst_CLK	(HPS_FLASH_DCLK),

				// Accelerometer
			   .hps_io_hps_io_gpio_inst_GPIO61	(HPS_GSENSOR_INT),

				// General Purpose I/O
				.hps_io_hps_io_gpio_inst_GPIO40	(HPS_GPIO[0]),
				.hps_io_hps_io_gpio_inst_GPIO41	(HPS_GPIO[1]),

				// I2C
				.hps_io_hps_io_gpio_inst_GPIO48	(HPS_I2C_CONTROL),
				.hps_io_hps_io_i2c0_inst_SDA		(HPS_I2C1_SDAT),
				.hps_io_hps_io_i2c0_inst_SCL		(HPS_I2C1_SCLK),
				.hps_io_hps_io_i2c1_inst_SDA		(HPS_I2C2_SDAT),
				.hps_io_hps_io_i2c1_inst_SCL		(HPS_I2C2_SCLK),

				// Pushbutton
				.hps_io_hps_io_gpio_inst_GPIO54	(HPS_KEY),

				// LED
				.hps_io_hps_io_gpio_inst_GPIO53	(HPS_LED), //HPS_LED

				// SD Card
				.hps_io_hps_io_sdio_inst_CMD	(HPS_SD_CMD),
				.hps_io_hps_io_sdio_inst_D0	(HPS_SD_DATA[0]),
				.hps_io_hps_io_sdio_inst_D1	(HPS_SD_DATA[1]),
				.hps_io_hps_io_sdio_inst_CLK	(HPS_SD_CLK),
				.hps_io_hps_io_sdio_inst_D2	(HPS_SD_DATA[2]),
				.hps_io_hps_io_sdio_inst_D3	(HPS_SD_DATA[3]),

				// SPI
				.hps_io_hps_io_spim1_inst_CLK		(HPS_SPIM_CLK),
				.hps_io_hps_io_spim1_inst_MOSI	(HPS_SPIM_MOSI),
				.hps_io_hps_io_spim1_inst_MISO	(HPS_SPIM_MISO),
				.hps_io_hps_io_spim1_inst_SS0		(HPS_SPIM_SS),

				// UART
				.hps_io_hps_io_uart0_inst_RX	(HPS_UART_RX),
				.hps_io_hps_io_uart0_inst_TX	(HPS_UART_TX),

				// USB
				.hps_io_hps_io_gpio_inst_GPIO09	(HPS_CONV_USB_N),
				.hps_io_hps_io_usb1_inst_D0		(HPS_USB_DATA[0]),
				.hps_io_hps_io_usb1_inst_D1		(HPS_USB_DATA[1]),
				.hps_io_hps_io_usb1_inst_D2		(HPS_USB_DATA[2]),
				.hps_io_hps_io_usb1_inst_D3		(HPS_USB_DATA[3]),
				.hps_io_hps_io_usb1_inst_D4		(HPS_USB_DATA[4]),
				.hps_io_hps_io_usb1_inst_D5		(HPS_USB_DATA[5]),
				.hps_io_hps_io_usb1_inst_D6		(HPS_USB_DATA[6]),
				.hps_io_hps_io_usb1_inst_D7		(HPS_USB_DATA[7]),
				.hps_io_hps_io_usb1_inst_CLK		(HPS_USB_CLKOUT),
				.hps_io_hps_io_usb1_inst_STP		(HPS_USB_STP),
				.hps_io_hps_io_usb1_inst_DIR		(HPS_USB_DIR),
				.hps_io_hps_io_usb1_inst_NXT		(HPS_USB_NXT),
		  
		  
			  // External
			  
			  .leds_export            		  (LEDR[9:0]),                  	//          ledr.export
			  .sw_export                    (SW[9:0]),                    	//            sw.export
			  .keys_export                  (KEY[3:0]),                   	//          keys.export
	 .my_display_7seg_out_dispa  (HEX0),             // display_out_dispa.out_dispa
	.my_display_7seg_out_dispb  (HEX1),             // display_out_dispb.out_dispb
	.my_display_7seg_out_dispc  (HEX2),             // display_out_dispc.out_dispc
	.my_display_7seg_out_dispd  (HEX3),             // display_out_dispd.out_dispd
	.my_display_7seg_out_dispe  (HEX4),             // display_out_dispe.out_dispe
	.my_display_7seg_out_dispf  (HEX5),             // display_out_dispf.out_dispf
	
   .encoder_data1         (GPIO1GPIO[0]),     // enc0.data1
.encoder_data2         (GPIO1GPIO[1]),     // enc0.data2
.encoder_data1_reg_out         (0),                // enc0.datar1
.encoder_data2_reg_out        (0),                // enc0.datar2

.key_export(GPIO1GPIO[2]),




	);

endmodule
